### PR TITLE
Begin gutting the old about pages

### PR DESCRIPTION
**Pull request by phil303**
A start on removing all the dead code from this repo, of
which there is a lot now. This isn't as complete as it
could be to limit the scope of the deletions. Plus I'm not
sure what this module should be called anymore so I stopped
short of variable renaming/handling a different namespace.

:eyeglasses: @MelissaCole @curioussavage

### CODE REVIEW

**Comment by curioussavage** [comment]
So is this only part of what will be removed?

**Comment by curioussavage** [comment]
I don't see any specific issues in the code. Maybe you could explain more. It looks like the only route that doesn't get redirected to about.reddit.com is `/about/postcards`? So does that leave this plugin with just postcards and the ads stuff then?

**Comment by curioussavage** [comment]
💅   just questions really

**Comment by phil303** [comment]
@curioussavage Yes, that's correct - only postcards and advertising lives here now. Obviously the naming is a little awkward and I'd like to address that eventually but am trying to keep the number of changes in this one patch down to a manageable level.  It'd also be nice to redirect `/about/postcards` to just `/postcards`.

**Comment by curioussavage** [comment]
lgtm. Maybe we should make sure @dwick or someone else from ads knows we are modifying the repo

**Comment by dwick** [comment]
looks fine to me.  we'll be moving /advertising elsewhere soon too :)

**Comment by curioussavage** [comment]
🐟

**Comment by MelissaCole** [comment]
:fish: :+1:

**Pull request closed without merging**
