### PR TITLE
Team page: use data from wiki

### PR DESCRIPTION
**Pull request by Deimos**
This switches to taking the data for the team page from the wiki, similar to how we do gold features/partners and some data on the advertising page (sorry, we'll need to figure out a new "first commit" for new employees). Before we deploy this, I'll write a conversion script that will go through the current team JSON and output the equivalent text for the INI format used on the wiki page. All existing snoos and mouseover versions will also need to be uploaded somewhere (probably just through /r/reddit.com).

The main significant change here is that we're dropping the "custom sorts". It seems that a lot of newer employees haven't had them anyway, and they have some bugs with alumni. I'm also unsure about the way I'm doing the mouseover image switch, I'm sure there's probably a better way to do it.

:eyeglasses: @umbrae @bsimpson63 

(and cc @powerlanguage)

### CODE REVIEW

**Comment by bsimpson63** [comment]
What's the motivation for this?

**Comment by Deimos** [comment]
The process for updating the team page just kind of sucks, so it gets put off for long periods of time, even though we should really be updating it more regularly as people join/leave. Having a spreadsheet output JSON, requiring code review and a deployment for simple text updates, etc.

Especially as the company keeps growing, I imagine that it'll become more and more common for people to want small text tweaks, updates to their list of favorite subreddits, etc. This makes that an extremely simple process that almost anyone can do, instead of needing to involve developers.

**Comment by Deimos** [comment]
Oh and also, like Matt pointed out yesterday, it's pretty weird that if an open-source user clones the plugin and doesn't specifically go in and clean out this data, a snapshot of reddit's team at that time ends up on their site, like http://reddit.greenmedinfo.com/about/team

**Comment by florenceyeun** [comment]
Why is the about plugin default for open-source?

**Comment by Deimos** [comment]
@florenceyeun: it's not included or enabled by default, but various people tend to pull it down and add it to their installs anyway. I'm not really sure why, since pretty much everything in it is very reddit.com-specific, but maybe they intend to try to replace it all with info about their own site. One consideration could be that the site footer includes some broken links by default because of it being missing, so they may be trying to fix those?

**Comment by florenceyeun** [comment]
@Deimos Maybe it's because about is provided as a default/example in https://github.com/reddit/reddit/blob/master/install-reddit.sh and https://github.com/reddit/reddit-vagrant?

**Comment by Deimos** [comment]
Oh wow, I actually didn't realize that the open-source install script cloned and installed plugins by default, I don't know if it should do that. I don't think the "meatspace" plugin should be relevant for anyone, though liveupdate might be reasonable to include. @spladug - should we remove some/all of those from being cloned as part of installation?

**Comment by spladug** [comment]
The goal of adding some plugins was to allow people to dev on them.  The install script sets up a dev environment, not production, so it's assumed that if you're going to production-ize you'll choose the plugins you actually want.  Before I added those plugins to the install script, I was getting occasional pings in #reddit-dev asking how to modify the about page or liveupdate or whatever.

(that said, meatspace can probably die. that project is seemingly long dead)

**Comment by bsimpson63** [comment]
:fish: seems reasonable

**Comment by bsimpson63** [comment]
There needs to be an ini change to set `wiki_page_team_members` right?

**Comment by Deimos** [comment]
Yes, will need a private change for that as well (I'll need to do that script to convert all the data for the page too).

**Comment by powerlanguage** [comment]
@Deimos Would it be possible to use another subreddit for the images? /r/reddit.com is already teeming with images, and adding another 80+ is going to make it really messy.

**Comment by Deimos** [comment]
Yeah, it doesn't matter at all where the images are stored, all you need is their urls.

**Comment by spladug** [comment]
:running: (cleaning up salon, sorry)

**Pull request merged**
