### PR TITLE
advertising: Make contact link in header point to typeform form.

### PR DESCRIPTION
**Pull request by madbook**
From ryan:

> madlee: can we switch out the managed email link on /advertising to http://bit.ly/redditadvertising ?

the answer is yes, ryan.

:eyeglasses: @dwick

### CODE REVIEW

**Comment by dwick** [comment]
:fish:

**Comment by rram** [comment]
a wild admin appears

it seems pretty shady to use a bit.ly link for this. I would much prefer adding in a redirect on the reddit side for this. (it can be done in haproxy if necessary)

**Comment by madbook** [comment]
@rram sales wants to use bit.ly for tracking clicks to get conversion rate.  if it seems to shady to you, I can switch it to fire a GA event instead

**Comment by rram** [comment]
I would prefer that. (or hivemind event). We discourage the use of link shorteners on our site, so we shouldn't use them ourselves. This also sounds easy enough to track in-house.

**Comment by madbook** [comment]
:haircut:

**Comment by dwick** [comment]
:nail_care: small thing

**Comment by madbook** [comment]
nice! wasn't aware of `closest`. :haircut:

**Comment by dwick** [comment]
:fish:

**Comment by madbook** [comment]
realized that I should queue the redirect to ensure that the GA event fires first.  @dwick changed this to use your `fireFunnelEvent` method, since it seems a little more flexible if we ever  wanted to change that link to point to an internal form, and also because your method handles queuing up the redirect callback :)

:haircut:

**Comment by dwick** [comment]
yeah, i'm taking this over. you can close if you want and i'll open a new PR when it's ready.

**Comment by madbook** [comment]
oh awesome, thanks!

**Pull request closed without merging**
