### PR TITLE
Show usernames instead of real names on team page.

### PR DESCRIPTION
**Pull request by powerlanguage**
:eyeglasses: @Deimos 

At Steve's suggestion.

No idea if this the best way to do this.  I'll need to go through and remove all the real names from the wiki.

### CODE REVIEW

**Comment by Deimos** [comment]
That should about cover it I think, yeah. I'm pretty sure this will cause the team page to break until all the `name =` lines are removed from the wiki, but on the other side removing those lines before deploying this will cause it to break too. It's probably not a big deal to have the team page broken for ~5 mins though, so I'd probably just go with this and then remove the lines after the deploy is complete.

:fish:

**Comment by powerlanguage** [comment]
:eyeglasses: @spez

Replace real names with usernames on team page

Before:
screenshot 2015-09-30 18 46 53

After:
screenshot 2015-09-30 18 47 21

**Comment by spez** [comment]
:fish: from me. would like to hear other's opinions

**Comment by spladug** [comment]
Just curious, what's the idea behind it? Is it a privacy thing? I can see it reducing the humanness of admins -- perhaps just showing first names would cover both cases?

**Comment by tdohz** [comment]
+1 first names and maybe last initial.

**Comment by spez** [comment]
The reasoning is two-fold:
1) we shouldn't be putting people's real names on the site without permission
2) it's fodder for recruiters
3) it gives away a lot of information, e.g. how many people work at Reddit

Long term, I want to re-do this page. In the short term, full names makes me uncomfortable. I can't see a reason to include them, but that's why I asked.

**Comment by ajacksified** [comment]
+1 @tdohz

**Comment by powerlanguage** [comment]
Updated the exiting team page to display first names only.  Doesn't require a code change.

**Pull request closed without merging**
